spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/template_goose_db?allowPublicKeyRetrieval=true&useSSL=false&nullNamePatternMatchesAll=true&maxReconnects=10&autoReconnect=true&characterEncoding=UTF-8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    testWhileIdle: true
    validationQuery: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: templateGooseCP
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 125
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: true
      max-lifetime: 1500000
      connection-timeout: 10000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml


logging:
  config: classpath:logback-spring.xml