spring:
  config:
    activate:
      on-profile: dev

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:templateIguanaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    testWhileIdle: true
    validationQuery: SELECT 1
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: templateIguanaCP
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 125
        prepStmtCacheSqlLimit: 1024
        useServerPrepStmts: true
      max-lifetime: 1500000
      connection-timeout: 10000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
